batch_size: 256
checkpoint_freq: 10000
conv_layers:
- - 8
  - 2
  - 1
- - 8
  - 2
  - 1
env_name: MiniGrid-Empty-5x5-v0
env_wrappers:
- FullyObsWrapper
- ImageChannelSwapWrapper
eps_decay: 20000
eps_end: 0.1
eps_start: 1.0
eval_eps: 10
eval_freq: 1000
gamma: 0.95
lr: 0.0003
matching_loss: bce
matching_loss_coef: 1.0
model: MultiHeadDQN
num_episodes: 5000
predicate_args:
- []
- []
- - 1
  - 1
- - 1
  - 2
- - 1
  - 3
- - 1
  - 4
- - 2
  - 1
- - 2
  - 2
- - 2
  - 3
- - 3
  - 1
- - 3
  - 2
- - 3
  - 3
predicates:
- FullyObservableMiniGridNextToWall
- FullyObservableMiniGridAwayFromWall
- FullyObservableMiniGrid5x5v0AtSquare
- FullyObservableMiniGrid5x5v0AtSquare
- FullyObservableMiniGrid5x5v0AtSquare
- FullyObservableMiniGrid5x5v0AtSquare
- FullyObservableMiniGrid5x5v0AtSquare
- FullyObservableMiniGrid5x5v0AtSquare
- FullyObservableMiniGrid5x5v0AtSquare
- FullyObservableMiniGrid5x5v0AtSquare
- FullyObservableMiniGrid5x5v0AtSquare
- FullyObservableMiniGrid5x5v0AtSquare
replay_buffer_size: 20000
seed: 3
target_update: 2000
temp_decay: 20000
temp_end: 0.1
temp_start: 1.0
update_freq: 1
wandb_project: rlexp_4256wk1m
wandb_tags: v1/4256wk1m/8
