config_for: horde

# Environment settings
env_name: 'MiniGrid-Empty-5x5-v0'
env_wrappers: ['FullyObsWrapper', 'ImageChannelSwapWrapper'] # The first wrapper wraps around the env first

# Randomization
seed:
  values: [1]

# Discounting
gamma: 0.95

# Exploration with epsilon greedy
eps_start: 1.0
eps_end: 0.1
eps_decay: 20000

# Boltzmann matching policy
temp_start: 1.0
temp_end: 0.1
temp_decay: 20000

# Model
model: Horde
dist_model: AttentionPolicyDistillation
policy: EpsilonGreedyPolicy

# Optimizer
optimizer: RMSprop
dist_optimizer: RMSprop

# Target network settings
target_update: 2000 # steps

# Number of episodes
num_episodes: 10000

# Evaluation settings
eval_freq: 1000 # steps
eval_eps: 3 # number of evaluation episodes
eval_dir: /export/share/karan-goel/rlexp/

n_attention_heads: 1

# Checkpoint settings
checkpoint_freq: 5000 # steps

# Replay buffer settings
replay_buffer_size: 20000

# Optimization settings
update_freq: 1 # steps
batch_size: 256
dist_batch_size: 32
lr: 0.0003
dist_lr: 0.001
dist_steps: 1

# Deep network settings
conv_layers: [[8, 2, 1], [8, 2, 1]]
batch_norm: False
detach_aux_demons: True

# Attention mechanism settings
detach_attn_context: True
distill_from_target_net: True
k_dim: 8
attn_mechanism:
  values: [lin_action_independent, lin_action_independent_with_state_concat,
           lin_state_action_concat, 2layer_state_action_concat, global_regression]
attn_softmax: False
affine_vals: False
fit_residuals: True

# Loss
regression_loss_fn: l2
regularization: l1
regularization_coef:
  values: [0.1]

# Predicates to use
predicates: [Constant, FullyObservableMiniGridNextToWall, FullyObservableMiniGridAwayFromWall, FullyObservableMiniGrid5x5v0AtSquare,
            FullyObservableMiniGrid5x5v0AtSquare, FullyObservableMiniGrid5x5v0AtSquare, FullyObservableMiniGrid5x5v0AtSquare,
            FullyObservableMiniGrid5x5v0AtSquare, FullyObservableMiniGrid5x5v0AtSquare, FullyObservableMiniGrid5x5v0AtSquare,
            FullyObservableMiniGrid5x5v0AtSquare, FullyObservableMiniGrid5x5v0AtSquare, FullyObservableMiniGrid5x5v0AtSquare]
predicate_args: [[], [], [], [1, 1],
                 [1, 2], [1, 3], [1, 4],
                 [2, 1], [2, 2], [2, 3],
                 [3, 1], [3, 2], [3, 3]]
# Weights and Biases configuration settings
wandb_org: salesforce
wandb_project: rlexp-horde-v2
wandb_tags: v2
