config_for: offline_horde

# Phase 1 information
phase_1_checkpoint: 4000000
phase_1_run_id: yiurhdqv

# Environment settings
env_name: 'MiniGrid-KeyCorridorS3R2-v0'
env_wrappers: ['FullyObsWrapper', 'ImageChannelSwapWrapper', 'MiniGridRewardWrapper', 'MiniGridTimeLimitWrapper']
env_wrapper_args: [[], [], [], [1000]]
n_envs: 512
reseed: True
reseed_strategy: same # within an env
seed_strategy: same # across the vector of envs

# Randomization
seed:
  values: [1, 2]

# Discounting
gamma:
  values: [0.99]

# Exploration with epsilon greedy
eps_start: 1.0
eps_end: 0.1
eps_decay:
  values: [2000000]

# Boltzmann matching policy
temp_start: 1.0
temp_end: 0.1
temp_decay: 20000

# Model
model: Horde
dist_model: AttentionPolicyDistillation
policy: EpsilonGreedyPolicy

# Optimizer
optimizer: RMSprop
dist_optimizer: RMSprop

# Target network settings
target_update:
  values: [5000] # steps (must be divided by n_envs)
q_target:
  values: [standard]

# Number of episodes
num_steps: 200000

# Evaluation settings
eval_freq: 1000 # steps
eval_eps: 3 # number of evaluation episodes
eval_policy: main
eval_dir: /export/share/karan-goel/rlexp/

n_attention_heads: 1

# Checkpoint settings
checkpoint_freq: 10000 # steps

# Replay buffer settings
replay_buffer_size:
  values: [10000000]
replay_buffer_alpha:
  values: [0.]
replay_buffer_beta_start: 0.5
replay_buffer_beta_end: 1.
replay_buffer_beta_decay: 20000000

# Optimization settings
update_freq: 1 # steps
batch_size: 1024
dist_batch_size: 64
lr:
  values: [0.001]
dist_lr: 0.001
dist_steps: 1

# Deep network settings
conv_layers: [[8, 2, 1], [8, 2, 1]]
batch_norm: False
detach_aux_demons: True

# Attention mechanism settings
detach_attn_context: True
distill_from_target_net: True
k_dim: 8
attn_mechanism:
  values: [lin_state_action_concat]
attn_softmax: False
affine_vals: False
fit_residuals: True

# Loss
regression_loss_fn: l2
regularization: l1
regularization_coef:
  values: [0.1]

# Predicates to use
predicates: [Constant, FullyObservableMiniGridPickUp, FullyObservableMiniGridPickUp,
             FullyObservableMiniGridAttemptOpenDoor, FullyObservableMiniGridNear, FullyObservableMiniGridNear,
             FullyObservableMiniGridNear]
predicate_args: [[], ['key'], ['ball'], [],
                 ['key', 1], ['door', 1], ['ball', 1]]


# Weights and Biases configuration settings
wandb_org: salesforce
wandb_project: rlexp-minigrid-keycorridor-s3r2-horde-v3
wandb_tags: v3