affine_vals: false
attn_mechanism: lin_state_action_concat
attn_softmax: false
batch_norm: false
batch_size: 256
checkpoint_freq: 5120
config_for: horde
conv_layers:
- - 8
  - 2
  - 1
- - 8
  - 2
  - 1
detach_attn_context: true
detach_aux_demons: true
dist_batch_size: 64
dist_lr: 0.001
dist_model: AttentionPolicyDistillation
dist_optimizer: RMSprop
dist_steps: 1
distill_from_target_net: true
env_name: MiniGrid-Empty-5x5-v0
env_wrapper_args:
- []
- []
- - 50
env_wrappers:
- FullyObsWrapper
- ImageChannelSwapWrapper
- TimeLimit
eps_decay: 20000
eps_end: 0.1
eps_start: 1.0
eval_dir: /export/share/karan-goel/rlexp/
eval_eps: 3
eval_freq: 1000
eval_policy: main
fit_residuals: true
gamma: 0.95
k_dim: 8
lr: 0.0001
model: Horde
n_attention_heads: 1
n_envs: 64
num_steps: 200000
optimizer: RMSprop
policy: EpsilonGreedyPolicy
predicate_args:
- []
- - goal
  - 1
- - goal
  - 2
- - goal
  - 3
predicates:
- Constant
- FullyObservableMiniGridNear
- FullyObservableMiniGridNear
- FullyObservableMiniGridNear
regression_loss_fn: l2
regularization: l1
regularization_coef: 0.1
replay_buffer_alpha: 0.0
replay_buffer_beta_decay: 100000
replay_buffer_beta_end: 1.0
replay_buffer_beta_start: 0.5
replay_buffer_size: 20000
reseed: true
reseed_strategy: same
seed: 1
seed_strategy: same
target_update: 2048
temp_decay: 20000
temp_end: 0.1
temp_start: 1.0
update_freq: 1
wandb_org: salesforce
wandb_project: rlexp-minigrid-empty-5x5-horde-v3
wandb_tags: v3/402ucqg4/15
